### ISSUE TITLE
Abone olma bölümünün zaman seçimi alanında text yanlış gözüküyor

### ISSUE THREAD

**Issue by sevkioruc** [kodilan-com/frontend#111]
**Describe the bug**
Abone olma bölümünde bulunan select' te üst üste aynı options seçildiği zaman yanlış davranıyor.
Örneğin iki kere 'haftalık' seçeneğini seçtiğim zaman 'Select option' yazısı yazıyor

**To Reproduce**
1. Abone olma komponentine git
2. Zaman seçimi bölümünden aynı seçeneği iki kere seç

**Expected behavior**
Seçilen seçeneğin text' inin yazması

**Screenshots**
![Screenshot 2020-09-13 013301](https://user-images.githubusercontent.com/33834689/93006432-c3478380-f564-11ea-9660-98b75c47f266.png)

**Comment by muhsin61** [comment]
Bu hata select'e çok hızlı tıklayınca oluyor. Bunun nedeni vue-multiselect data içindeki frequencyOptions ulaşamayınca select-option yazısı çıkıyor. Eğer data'dan çekmek yerine options propsunu kendimiz yazarsak hızlı tıklayınca sorun ortadan kalkıyor ama bu durum temiz kod yazımına uymadığı için Pull requests açmadım belki farklı bir yolu vardır.
