### ISSUE TITLE
Add unit tests to Travis and generate coverage badge

### ISSUE THREAD

**Issue by fatihacet** [kodilan-com/frontend#30]
With [this PR](https://github.com/kodilan-com/frontend/pull/18) we added Jest unit tests. Now we should add unit tests to Travis pipeline as the first step. Then we should generate a coverage report and add coverage badge to README.

**Comment by fatihacet** [comment]
@erdoganbulut assigning this one to you. Can you please take a look?

**Comment by fatihacet** [comment]
@erdoganbulut @abdullah commented on the #18 about how we can generate a coverage report. You can take a look at it.

**Comment by erdoganbulut** [comment]
Thanks @fatihacet , I'm starting to work on this.

**Comment by fatihacet** [comment]
I just completed this task.

It's amazing to see that we have 71% test coverage. Thanks to @mersanuzun and thanks @abdullah for the reviews.

**Comment by mersanuzun** [comment]
I just saw the `.travis.yml` the file that configured with `yarn test:clear:snapshot`. Is it good to add there? Because this line updates the snapshots. If we update the snapshots before running tests, we would not catch the failed tests correctly. Am I wrong? @fatihacet

**Comment by fatihacet** [comment]
Oh, that’s right. It’s my bad. @mersanuzun can you please create a separate PR so I can merge immediately.
