### ISSUE TITLE
Backend is not open source

### ISSUE THREAD

**Issue by devfarmazon** [kodilan-com/frontend#31]
This is a very valuable project for Vue community. If you open backend to the world, ı think the project will have more power.

**Comment by fatihacet** [comment]
Hey @devfarmazon 👋 we want to open source our backend at some point in the future but don’t know when it will be.

Thank you for finding this project valuable to the community. That’s exactly why we open source kodilan.

I will close this issue for now and hope to comment back in the near future with good news.
