### ISSUE TITLE
QA issue for v1.2.0

### ISSUE THREAD

**Issue by fatihacet** [kodilan-com/frontend#35]
- [x] @fatihacet [Add support; save and use some addjob formdata parameters to localstorage.](https://github.com/kodilan-com/frontend/pull/29)
- [ ] @fatihacet [Use vue multiselect](https://github.com/kodilan-com/frontend/pull/15)
- [x] @fatihacet [Implement period selector](https://github.com/kodilan-com/frontend/pull/23)
- [ ] @fatihacet [Feature/searchable multiselect ui](https://github.com/kodilan-com/frontend/pull/19)
- [x] @fatihacet [Feature/unit test](https://github.com/kodilan-com/frontend/pull/18)
- [x] @fatihacet [Add issue templates](https://github.com/kodilan-com/frontend/pull/34)
- [x] @erdoganbulut [Add link to company logo in job details page](https://github.com/kodilan-com/frontend/pull/33)
- [x] @erdoganbulut [Close Subscribe component after user subscribed](https://github.com/kodilan-com/frontend/pull/28)
- [x] @erdoganbulut [Fix job listing margin problem on when few products](https://github.com/kodilan-com/frontend/pull/27)
- [x] @erdoganbulut [Bug/description widget margin](https://github.com/kodilan-com/frontend/pull/22)
- [x] @erdoganbulut [Check not found page](https://github.com/kodilan-com/frontend/pull/17)

**Comment by fatihacet** [comment]
I would love to thank everyone who contributed to this release. 

@erdoganbulut @mersanuzun @abdullah @obulat @bskl @ilker0 @furkankose @alibesinci  @aligoren @TugayYaldiz  @AliBiberoglu

:+1:

**Comment by obulat** [comment]
Thank you, @erdoganbulut and @fatihacet,  for mentioning and for kind guidance.

**Comment by fatihacet** [comment]
[Searchable select component issues](https://github.com/kodilan-com/frontend/issues/41) follow up issue created for the [Feature/searchable multiselect ui](https://github.com/kodilan-com/frontend/pull/19) /cc @erdoganbulut
