### ISSUE TITLE
There is no date on job details

### ISSUE THREAD

**Issue by eislambey** [kodilan-com/frontend#49]
On job details page i can't see the post time of a job. So i should go back for seeing when the job posted.

There is a date for `JobPosting` schema but no for users.
https://github.com/kodilan-com/frontend/blob/master/src/components/pages/JobDetails.vue#L225

**Comment by fatihacet** [comment]
Added to job overview widget. Thanks to @berkansivri 👍 

![image](https://user-images.githubusercontent.com/712419/63127349-cd423000-bfba-11e9-9297-03fb819cc9b3.png)
