### ISSUE TITLE
use-async-for-actions

### ISSUE THREAD

**Issue by wuruthai** [kodilan-com/frontend#6]
Use async/await for some http request 
     Use parameters for actions for creating axios url
     Make new line after per action

example:

`async fetchFeaturedPosts({ commit }, params = { get: 3, is_featured: 1 }) {
    const result = await http.get('/posts', { params });
    commit(constants.SET_FEATURED, result.data.data);
    return result.data;
  }`

**Comment by fatihacet** [comment]
@wuruthai thanks for creating the issue but I will close this one to prevent any possible further effort on this one.

I simply don't want to have/use async/await in our codebase. This may be an opinionated decision but no async/await for now.
